name: addstream_flutter
description: "A Flutter package for displaying AddStream ads in your mobile applications."
version: 1.1.0
homepage: https://addstream.net/
repository: https://github.com/Hayan47/addstream_flutter
issue_tracker: https://github.com/Hayan47/addstream_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audio_session: ^0.1.0
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  html: ^0.15.6
  http: ^1.5.0
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
   assets:
     - assets/logo.png